services:
  - addr: "http://:80"
    name: "web"
    auth:
      type: "aes"
      aes:
        key: "12345678901234567890123456789012"
      header: "User-Id"
      source:
        - type: "header"
          name: "Authorization"
        - type: "cookie"
          name: "token"
    module_config: "./modules/web"
  - addr: "http://:3000"
    name: "internal"
    module_config: "./modules/internalWeb"