addr: ":8088"
module_config: "./modules"
auth:
  type: "aes"
  aes:
    key: "12345678901234567890123456789012"
  header: "User-Id"
  source:
    - type: "header"
      name: "Authorization"
    - type: "cookie"
      name: "token"