instances:
  - name: "user-web"
    exec:
      - "./modules/user/user.exe"
      - "web"
      - "--config"
      - "./config.yaml"
  - name: "user-internal"
    exec:
      - "./modules/user/user.exe"
      - "internalWeb"
      - "--config"
      - "./config-internal.yaml"
  - name: "category-web"
    exec:
      - "./modules/category/main.exe"
      - "web"
      - "--config"
      - "./config.yaml"
  - name: "category-internal"
    exec:
      - "./modules/category/main.exe"
      - "internalWeb"
      - "--config"
      - "./config-internal.yaml"
  - name: "tag-web"
    exec:
      - "./modules/category/main.exe"
      - "web"
      - "--config"
      - "./tag.yaml"
  - name: "tag-internal"
    exec:
      - "./modules/category/main.exe"
      - "internalWeb"
      - "--config"
      - "./tag-internal.yaml"
  - name: "content-web"
    exec:
      - "./modules/content/main.exe"
      - "web"
      - "--config"
      - "./config.yaml"
  - name: "content-internal"
    exec:
      - "./modules/content/main.exe"
      - "internalWeb"
      - "--config"
      - "./config-internal.yaml"

services:
  - name: "internal-api"
    ports:
      - type: http
        http:
          host: "127.0.0.1"
          port: 3000
    routes:
      - name: user-internal-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/user/user-internal.sock
        rewrite:
          regex: "/api/user/(.*)"
          replace: "/$1"
        paths:
          - "/api/user/info/batch"
      - name: category-internal-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/category/category-internal.sock
        rewrite:
          regex: "/api/category/(.*)"
          replace: "/$1"
        paths:
          - "/api/category/create"
          - "/api/category/update"
          - "/api/category/batch"
      - name: tag-internal-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/category/tag-internal.sock
        rewrite:
          regex: "/api/tag/(.*)"
          replace: "/$1"
        paths:
          - "/api/tag/create"
          - "/api/tag/update"
          - "/api/tag/batch"
      - name: article-internal-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/content/internal.sock
        rewrite:
          regex: "/api/article/(.*)"
          replace: "/$1"
        paths:
          - "/api/article/create"
          - "/api/article/update"

  - name: "web-api"
    auth:
      type: aes
      aes:
        key: "12345678901234567890123456789012"
      header: "User-Id"
      source:
        - type: "header"
          name: "Authorization"
        - type: "cookie"
          name: "token"
    ports:
      - type: http
        http:
          port: 80
    rewrite:
      regex: "/api/user/(.*)"
      replace: "/$1"
    routes:
      - name: user-no-auth
        endpoints:
          - type: unix
            unix:
              path: ./modules/user/user.sock
        rewrite:
          regex: "/api/user/(.*)"
          replace: "/$1"
        paths:
          - "/api/user/access_token"
          - "/api/user/create"
          - "/api/user/info"
      - name: user-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/user/user.sock
        rewrite:
          regex: "/api/user(.*)"
          replace: "$1"
        auth: true
        paths:
          - "/api/user"
      - name: category-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/category/category.sock
        rewrite:
          regex: "/api/category/(.*)"
          replace: "/$1"
        paths:
          - "/api/category/children"
          - "/api/category/tree"
      - name: tag-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/category/tag.sock
        rewrite:
          regex: "/api/tag/(.*)"
          replace: "/$1"
        paths:
          - "/api/tag/children"
          - "/api/tag/tree"
      - name: article-api
        endpoints:
          - type: unix
            unix:
              path: ./modules/content/main.sock
        rewrite:
          regex: "/api/article/(.*)"
          replace: "/$1"
        paths:
          - "/api/article/list"
          - "/api/article"