components:
  - name: user-center
    exec:
      - "./components/user/main.exe"
      - "web"
      - "--config"
      - "./config.yaml"

http-authorization:
  type: aes-token
  header: User-Id
  source:
    header: Authorization
    cookie: access_token
    query: access_token
  ase-token:
    key: "12345678901234567890123456789012"

http-router:
  - name: admin-api
    hostname:
      - admin.dxkite.cn
    authorization: true
    endpoints:
      - http://127.0.0.1:8080
    rewrite:
      regex: "/admin/(.*)"
      replace: "/$1"
    paths:
      - /admin
  - name: simple-api
    authorization: true
    endpoints:
      - http://127.0.0.1:8080
    paths:
      - /api
  - name: user-no-auth
    endpoints:
      - http://127.0.0.1:8080
    paths:
      - /api/user/create-access-token
      - /api/user/create
      - /api/user/public-information
  - name: vue-frontend
    endpoints:
      - http://127.0.0.1:8080
  - name: go-get-helper
    endpoints:
      - http://127.0.0.1:8080
    matches:
      query: go-get=1
