components:
  - name: "user-web"
    exec:
      - "./components/user/main.exe"
      - "web"
      - "--config"
      - "./config.yaml"
  - name: "user-internal"
    exec:
      - "./components/user/main.exe"
      - "internalWeb"
      - "--config"
      - "./config-internal.yaml"
  - name: "category-web"
    exec:
      - "./components/category/main.exe"
      - "web"
      - "--config"
      - "./config.yaml"
  - name: "category-internal"
    exec:
      - "./components/category/main.exe"
      - "internalWeb"
      - "--config"
      - "./config-internal.yaml"

listen: "http://:80"

http-authorization:
  type: aes-token
  header: User-Id
  source:
    header:
      - Authorization
    cookie:
      - access_token
    query:
     - access_token
  aes-token:
    key: "12345678901234567890123456789012"

http-router:
  - name: simple-api
    authorization: true
    endpoints:
      - http://127.0.0.1:8080
    paths:
      - /api
  - name: user-no-auth
    endpoints:
      - http://127.0.0.1:8080
    paths:
      - /api/user/create-access-token
      - /api/user/create
      - /api/user/public-information
  - name: vue-frontend
    endpoints:
      - http://127.0.0.1:8082
  - name: user-no-auth-feature
    endpoints:
      - unix://./components/user/user-internal.sock
    matcher:
      query: feature=1
    paths:
      - /api/user/create-access-token
